version: '3.8'

services:
  web_app:
    build: .
    command: "python3 manage.py runserver 0.0.0.0:9999"
    volumes:
      - "./:/app"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    ports:
      - "9999:9999"

  celery_worker:
    build: .
    command: "celery -A core worker -l INFO"
    volumes:
      - "./:/app"
    depends_on:
      - redis
      - db

  celery_beat:
    build: .
    command: "celery -A core beat -l info"
    volumes:
      - "./:/app"
    depends_on:
      - redis
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - ./db_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    restart: always
    ports:
      - "5434:5432"

  redis:
    image: redis:6-alpine

volumes:
  db_data: